name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and run contains
      run: |
        docker compose build
        docker compose up -d
      
    - name: Run tests
      run: |
        docker compose exec -T backend pytest -v
    

    - name: Cleanup
      run: docker compose down